```yaml
# .github/workflows/docker-publish.yml

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/zadanie-drugie
  CACHE_IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/zadanie-drugie-cache:buildcache

name: Build and Publish Multi-Arch Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read      # potrzebne do checkout
      packages: write     # potrzebne do push do GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to DockerHub for cache
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max

      - name: Image digest
        run: |
          echo "Image pushed with digest: $(docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:latest --format '{{ .Digest }}')"
```
